export const LOAD_PROFESSORS_All_SUCCESS = "LOAD_PROFESSORS_ALL_SUCCESS";
export const LOAD_PROFESSORS_SUCCESS = "LOAD_PROFESSORS_SUCCESS";
export const CREATE_PROFESSOR = "CREATE_PROFESSOR";
export const LOAD_PROFESSORS_DATA_SUCCESS = "LOAD_PROFESSORS_DATA_SUCCESS";
export const CREATE_PROFESSOR_SUCCESS = "CREATE_PROFESSORS_SUCCESS";
export const UPDATE_PROFESSOR_SUCCESS = "UPDATE_PROFESSORS_SUCCESS";
export const DELETE_PROFESSOR_OPTIMISTIC = "DELETE_PROFESSORS_OPTIMISTIC";

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_DATA_SUCCESS = "LOAD_COURSES_DATA_SUCCESS";
export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";


export const LOAD_CLIENTES_All_SUCCESS = "LOAD_CLIENTES_All_SUCCESS";
export const LOAD_CLIENTES_SUCCESS = "LOAD_CLIENTES_SUCCESS";
export const LOAD_CLIENTES_DATA_SUCCESS = "LOAD_CLIENTES_DATA_SUCCESS";
export const CREATE_CLIENTE_SUCCESS = "CREATE_CLIENTE_SUCCESS";
export const UPDATE_CLIENTE_SUCCESS = "UPDATE_CLIENTE_SUCCESS";
export const DELETE_CLIENTE_OPTIMISTIC = "DELETE_CLIENTE_OPTIMISTIC";

export const LOAD_CLIENTES_All_SUCCESS = "LOAD_CLIENTES_All_SUCCESS";
export const LOAD_CLIENTES_SUCCESS = "LOAD_CLIENTES_SUCCESS";
export const LOAD_CLIENTES_DATA_SUCCESS = "LOAD_CLIENTES_DATA_SUCCESS";
export const CREATE_CLIENTE_SUCCESS = "CREATE_CLIENTE_SUCCESS";
export const UPDATE_CLIENTE_SUCCESS = "UPDATE_CLIENTE_SUCCESS";
export const DELETE_CLIENTE_OPTIMISTIC = "DELETE_CLIENTE_OPTIMISTIC";

export const LOAD_MOVIMIENTOS_All_SUCCESS = "LOAD_MOVIMIENTOS_All_SUCCESS";
export const LOAD_MOVIMIENTOS_SUCCESS = "LOAD_MOVIMIENTOS_SUCCESS";
export const LOAD_MOVIMIENTOS_DATA_SUCCESS = "LOAD_MOVIMIENTOS_DATA_SUCCESS";
export const CREATE_MOVIMIENTO_SUCCESS = "CREATE_MOVIMIENTO_SUCCESS";
export const UPDATE_MOVIMIENTO_SUCCESS = "UPDATE_MOVIMIENTO_SUCCESS";
export const DELETE_MOVIMIENTO_OPTIMISTIC = "DELETE_MOVIMIENTO_OPTIMISTIC";

export const LOAD_TRANSACCIONES_All_SUCCESS = "LOAD_TRANSACCIONES_All_SUCCESS";
export const LOAD_TRANSACCIONES_SUCCESS = "LOAD_TRANSACCIONES_SUCCESS";
export const LOAD_TRANSACCIONES_DATA_SUCCESS = "LOAD_TRANSACCIONES_DATA_SUCCESS";
export const CREATE_TRANSACCIONES_SUCCESS = "CREATE_TRANSACCIONES_SUCCESS";
export const UPDATE_TRANSACCIONES_SUCCESS = "UPDATE_TRANSACCIONES_SUCCESS";
export const DELETE_TRANSACCIONES_OPTIMISTIC = "DELETE_TRANSACCIONES_OPTIMISTIC";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_LIST="LOAD_LIST";

// By convention, actions that end in "_SUCCESS" are assumed to have been the result of a completed
// API call. But since we're doing an optimistic delete, we're hiding loading state.
// So this action name deliberately omits the "_SUCCESS" suffix.
// If it had one, our apiCallsInProgress counter would be decremented below zero
// because we're not incrementing the number of apiCallInProgress when the delete request begins.

export const LOAD_PRODUCTOS_All_SUCCESS = "LOAD_PRODUCTOS_ALL_SUCCESS";
export const LOAD_PRODUCTOS_SUCCESS = "LOAD_PRODUCTOS_SUCCESS";
export const CREATE_PRODUCTO = "CREATE_PRODUCTO";
export const LOAD_PRODUCTOS_DATA_SUCCESS = "LOAD_PRODUCTOS_DATA_SUCCESS";
export const CREATE_PRODUCTO_SUCCESS = "CREATE_PRODUCTOS_SUCCESS";
export const UPDATE_PRODUCTO_SUCCESS = "UPDATE_PRODUCTOS_SUCCESS";
export const DELETE_PRODUCTO_OPTIMISTIC = "DELETE_PRODUCTOS_OPTIMISTIC";